//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 07:53:52 PM CET 
//


package net.bncf.uol2010.utility.xsd.authentication;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.bncf.uol2010.utility.xsd.authentication package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.bncf.uol2010.utility.xsd.authentication
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Anagrafica }
     * 
     */
    public Anagrafica createAnagrafica() {
        return new Anagrafica();
    }

    /**
     * Create an instance of {@link Autorizzazioni }
     * 
     */
    public Autorizzazioni createAutorizzazioni() {
        return new Autorizzazioni();
    }

    /**
     * Create an instance of {@link Utente }
     * 
     */
    public Utente createUtente() {
        return new Utente();
    }

    /**
     * Create an instance of {@link net.bncf.uol2010.utility.xsd.authentication.Login }
     * 
     */
    public net.bncf.uol2010.utility.xsd.authentication.Login createLogin() {
        return new net.bncf.uol2010.utility.xsd.authentication.Login();
    }

    /**
     * Create an instance of {@link Anagrafica.Login }
     * 
     */
    public Anagrafica.Login createAnagraficaLogin() {
        return new Anagrafica.Login();
    }

    /**
     * Create an instance of {@link Autorizzazioni.Diritto }
     * 
     */
    public Autorizzazioni.Diritto createAutorizzazioniDiritto() {
        return new Autorizzazioni.Diritto();
    }

    /**
     * Create an instance of {@link Utente.MsgError }
     * 
     */
    public Utente.MsgError createUtenteMsgError() {
        return new Utente.MsgError();
    }

}
