//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:38:28 PM CEST 
//


package net.bncf.uol2010.utility.xsd.stampante;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idUtente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cognome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}colore" minOccurs="0"/>
 *         &lt;element name="rigaVerticale" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="rigaOrizzontale" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="autorizzazione" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="dataInizio" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                 &lt;attribute name="dataFine" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                 &lt;attribute name="codiceTipo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}barcode" minOccurs="0"/>
 *         &lt;element name="professione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="residenza" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="indirizzo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="citta" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="paese" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="domicilio" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="indirizzo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="citta" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="telefono" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="nascita" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="luogo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="data" type="{http://www.w3.org/2001/XMLSchema}date" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="documento" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="numeroDocumento" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="autoritaRilascio" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dataGiorno" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idUtente",
    "cognome",
    "nome",
    "colore",
    "rigaVerticale",
    "rigaOrizzontale",
    "autorizzazione",
    "barcode",
    "professione",
    "residenza",
    "domicilio",
    "nascita",
    "documento",
    "dataGiorno",
    "email"
})
@XmlRootElement(name = "anagraficaUtente")
public class AnagraficaUtente {

    @XmlElement(required = true)
    protected String idUtente;
    @XmlElement(required = true)
    protected String cognome;
    @XmlElement(required = true)
    protected String nome;
    @XmlSchemaType(name = "anyURI")
    protected String colore;
    @XmlSchemaType(name = "anyURI")
    protected String rigaVerticale;
    @XmlSchemaType(name = "anyURI")
    protected String rigaOrizzontale;
    protected AnagraficaUtente.Autorizzazione autorizzazione;
    @XmlSchemaType(name = "anyURI")
    protected String barcode;
    protected String professione;
    protected AnagraficaUtente.Residenza residenza;
    protected AnagraficaUtente.Domicilio domicilio;
    protected AnagraficaUtente.Nascita nascita;
    protected AnagraficaUtente.Documento documento;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataGiorno;
    protected String email;

    /**
     * Gets the value of the idUtente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdUtente() {
        return idUtente;
    }

    /**
     * Sets the value of the idUtente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdUtente(String value) {
        this.idUtente = value;
    }

    /**
     * Gets the value of the cognome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCognome() {
        return cognome;
    }

    /**
     * Sets the value of the cognome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCognome(String value) {
        this.cognome = value;
    }

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the colore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColore() {
        return colore;
    }

    /**
     * Sets the value of the colore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColore(String value) {
        this.colore = value;
    }

    /**
     * Gets the value of the rigaVerticale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRigaVerticale() {
        return rigaVerticale;
    }

    /**
     * Sets the value of the rigaVerticale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRigaVerticale(String value) {
        this.rigaVerticale = value;
    }

    /**
     * Gets the value of the rigaOrizzontale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRigaOrizzontale() {
        return rigaOrizzontale;
    }

    /**
     * Sets the value of the rigaOrizzontale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRigaOrizzontale(String value) {
        this.rigaOrizzontale = value;
    }

    /**
     * Gets the value of the autorizzazione property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaUtente.Autorizzazione }
     *     
     */
    public AnagraficaUtente.Autorizzazione getAutorizzazione() {
        return autorizzazione;
    }

    /**
     * Sets the value of the autorizzazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaUtente.Autorizzazione }
     *     
     */
    public void setAutorizzazione(AnagraficaUtente.Autorizzazione value) {
        this.autorizzazione = value;
    }

    /**
     * Gets the value of the barcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * Sets the value of the barcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarcode(String value) {
        this.barcode = value;
    }

    /**
     * Gets the value of the professione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfessione() {
        return professione;
    }

    /**
     * Sets the value of the professione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfessione(String value) {
        this.professione = value;
    }

    /**
     * Gets the value of the residenza property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaUtente.Residenza }
     *     
     */
    public AnagraficaUtente.Residenza getResidenza() {
        return residenza;
    }

    /**
     * Sets the value of the residenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaUtente.Residenza }
     *     
     */
    public void setResidenza(AnagraficaUtente.Residenza value) {
        this.residenza = value;
    }

    /**
     * Gets the value of the domicilio property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaUtente.Domicilio }
     *     
     */
    public AnagraficaUtente.Domicilio getDomicilio() {
        return domicilio;
    }

    /**
     * Sets the value of the domicilio property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaUtente.Domicilio }
     *     
     */
    public void setDomicilio(AnagraficaUtente.Domicilio value) {
        this.domicilio = value;
    }

    /**
     * Gets the value of the nascita property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaUtente.Nascita }
     *     
     */
    public AnagraficaUtente.Nascita getNascita() {
        return nascita;
    }

    /**
     * Sets the value of the nascita property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaUtente.Nascita }
     *     
     */
    public void setNascita(AnagraficaUtente.Nascita value) {
        this.nascita = value;
    }

    /**
     * Gets the value of the documento property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaUtente.Documento }
     *     
     */
    public AnagraficaUtente.Documento getDocumento() {
        return documento;
    }

    /**
     * Sets the value of the documento property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaUtente.Documento }
     *     
     */
    public void setDocumento(AnagraficaUtente.Documento value) {
        this.documento = value;
    }

    /**
     * Gets the value of the dataGiorno property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataGiorno() {
        return dataGiorno;
    }

    /**
     * Sets the value of the dataGiorno property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataGiorno(XMLGregorianCalendar value) {
        this.dataGiorno = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="dataInizio" type="{http://www.w3.org/2001/XMLSchema}date" />
     *       &lt;attribute name="dataFine" type="{http://www.w3.org/2001/XMLSchema}date" />
     *       &lt;attribute name="codiceTipo" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Autorizzazione {

        @XmlAttribute
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dataInizio;
        @XmlAttribute
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dataFine;
        @XmlAttribute
        protected String codiceTipo;

        /**
         * Gets the value of the dataInizio property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDataInizio() {
            return dataInizio;
        }

        /**
         * Sets the value of the dataInizio property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDataInizio(XMLGregorianCalendar value) {
            this.dataInizio = value;
        }

        /**
         * Gets the value of the dataFine property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDataFine() {
            return dataFine;
        }

        /**
         * Sets the value of the dataFine property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDataFine(XMLGregorianCalendar value) {
            this.dataFine = value;
        }

        /**
         * Gets the value of the codiceTipo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodiceTipo() {
            return codiceTipo;
        }

        /**
         * Sets the value of the codiceTipo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodiceTipo(String value) {
            this.codiceTipo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="numeroDocumento" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="autoritaRilascio" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Documento {

        @XmlAttribute
        protected String tipo;
        @XmlAttribute
        protected String numeroDocumento;
        @XmlAttribute
        protected String autoritaRilascio;

        /**
         * Gets the value of the tipo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipo() {
            return tipo;
        }

        /**
         * Sets the value of the tipo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipo(String value) {
            this.tipo = value;
        }

        /**
         * Gets the value of the numeroDocumento property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumeroDocumento() {
            return numeroDocumento;
        }

        /**
         * Sets the value of the numeroDocumento property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumeroDocumento(String value) {
            this.numeroDocumento = value;
        }

        /**
         * Gets the value of the autoritaRilascio property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAutoritaRilascio() {
            return autoritaRilascio;
        }

        /**
         * Sets the value of the autoritaRilascio property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAutoritaRilascio(String value) {
            this.autoritaRilascio = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="indirizzo" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="citta" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="telefono" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Domicilio {

        @XmlAttribute
        protected String indirizzo;
        @XmlAttribute
        protected String citta;
        @XmlAttribute
        protected String telefono;

        /**
         * Gets the value of the indirizzo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIndirizzo() {
            return indirizzo;
        }

        /**
         * Sets the value of the indirizzo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIndirizzo(String value) {
            this.indirizzo = value;
        }

        /**
         * Gets the value of the citta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCitta() {
            return citta;
        }

        /**
         * Sets the value of the citta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCitta(String value) {
            this.citta = value;
        }

        /**
         * Gets the value of the telefono property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelefono() {
            return telefono;
        }

        /**
         * Sets the value of the telefono property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTelefono(String value) {
            this.telefono = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="luogo" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="data" type="{http://www.w3.org/2001/XMLSchema}date" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Nascita {

        @XmlAttribute
        protected String luogo;
        @XmlAttribute
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar data;

        /**
         * Gets the value of the luogo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLuogo() {
            return luogo;
        }

        /**
         * Sets the value of the luogo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLuogo(String value) {
            this.luogo = value;
        }

        /**
         * Gets the value of the data property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getData() {
            return data;
        }

        /**
         * Sets the value of the data property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setData(XMLGregorianCalendar value) {
            this.data = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="indirizzo" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="citta" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="paese" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Residenza {

        @XmlAttribute
        protected String indirizzo;
        @XmlAttribute
        protected String citta;
        @XmlAttribute
        protected String paese;

        /**
         * Gets the value of the indirizzo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIndirizzo() {
            return indirizzo;
        }

        /**
         * Sets the value of the indirizzo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIndirizzo(String value) {
            this.indirizzo = value;
        }

        /**
         * Gets the value of the citta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCitta() {
            return citta;
        }

        /**
         * Sets the value of the citta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCitta(String value) {
            this.citta = value;
        }

        /**
         * Gets the value of the paese property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaese() {
            return paese;
        }

        /**
         * Sets the value of the paese property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaese(String value) {
            this.paese = value;
        }

    }

}
