//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:38:28 PM CEST 
//


package net.bncf.uol2010.utility.xsd.stampante;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idRichiesta" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="autore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="titolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pubblica" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="annoPeriodico" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}localizzazione"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idRichiesta",
    "autore",
    "titolo",
    "pubblica",
    "annoPeriodico",
    "localizzazione"
})
@XmlRootElement(name = "datiBibliografici")
public class DatiBibliografici {

    protected int idRichiesta;
    @XmlElement(required = true)
    protected String autore;
    @XmlElement(required = true)
    protected String titolo;
    @XmlElement(required = true)
    protected String pubblica;
    @XmlElement(required = true)
    protected String annoPeriodico;
    @XmlElement(required = true)
    protected Localizzazione localizzazione;

    /**
     * Gets the value of the idRichiesta property.
     * 
     */
    public int getIdRichiesta() {
        return idRichiesta;
    }

    /**
     * Sets the value of the idRichiesta property.
     * 
     */
    public void setIdRichiesta(int value) {
        this.idRichiesta = value;
    }

    /**
     * Gets the value of the autore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutore() {
        return autore;
    }

    /**
     * Sets the value of the autore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutore(String value) {
        this.autore = value;
    }

    /**
     * Gets the value of the titolo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitolo() {
        return titolo;
    }

    /**
     * Sets the value of the titolo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitolo(String value) {
        this.titolo = value;
    }

    /**
     * Gets the value of the pubblica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubblica() {
        return pubblica;
    }

    /**
     * Sets the value of the pubblica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubblica(String value) {
        this.pubblica = value;
    }

    /**
     * Gets the value of the annoPeriodico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnoPeriodico() {
        return annoPeriodico;
    }

    /**
     * Sets the value of the annoPeriodico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnoPeriodico(String value) {
        this.annoPeriodico = value;
    }

    /**
     * Gets the value of the localizzazione property.
     * 
     * @return
     *     possible object is
     *     {@link Localizzazione }
     *     
     */
    public Localizzazione getLocalizzazione() {
        return localizzazione;
    }

    /**
     * Sets the value of the localizzazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link Localizzazione }
     *     
     */
    public void setLocalizzazione(Localizzazione value) {
        this.localizzazione = value;
    }

}
