//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:38:28 PM CEST 
//


package net.bncf.uol2010.utility.xsd.stampante;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="segnatura" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="consistenza" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inventario" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="precisazione" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "segnatura",
    "consistenza",
    "inventario",
    "precisazione"
})
@XmlRootElement(name = "localizzazione")
public class Localizzazione {

    @XmlElement(required = true)
    protected String segnatura;
    @XmlElement(required = true)
    protected String consistenza;
    @XmlElement(required = true)
    protected String inventario;
    @XmlElement(required = true)
    protected String precisazione;

    /**
     * Gets the value of the segnatura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegnatura() {
        return segnatura;
    }

    /**
     * Sets the value of the segnatura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegnatura(String value) {
        this.segnatura = value;
    }

    /**
     * Gets the value of the consistenza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsistenza() {
        return consistenza;
    }

    /**
     * Sets the value of the consistenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsistenza(String value) {
        this.consistenza = value;
    }

    /**
     * Gets the value of the inventario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventario() {
        return inventario;
    }

    /**
     * Sets the value of the inventario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventario(String value) {
        this.inventario = value;
    }

    /**
     * Gets the value of the precisazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrecisazione() {
        return precisazione;
    }

    /**
     * Sets the value of the precisazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrecisazione(String value) {
        this.precisazione = value;
    }

}
