//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:38:28 PM CEST 
//


package net.bncf.uol2010.utility.xsd.stampante;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.bncf.xsd.stampante package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Colore_QNAME = new QName("", "colore");
    private final static QName _Barcode_QNAME = new QName("", "barcode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.bncf.xsd.stampante
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Stampante }
     * 
     */
    public Stampante createStampante() {
        return new Stampante();
    }

    /**
     * Create an instance of {@link Richiesta }
     * 
     */
    public Richiesta createRichiesta() {
        return new Richiesta();
    }

    /**
     * Create an instance of {@link AnagraficaUtente.Domicilio }
     * 
     */
    public AnagraficaUtente.Domicilio createAnagraficaUtenteDomicilio() {
        return new AnagraficaUtente.Domicilio();
    }

    /**
     * Create an instance of {@link Localizzazione }
     * 
     */
    public Localizzazione createLocalizzazione() {
        return new Localizzazione();
    }

    /**
     * Create an instance of {@link AnagraficaUtente }
     * 
     */
    public AnagraficaUtente createAnagraficaUtente() {
        return new AnagraficaUtente();
    }

    /**
     * Create an instance of {@link AnagraficaUtente.Autorizzazione }
     * 
     */
    public AnagraficaUtente.Autorizzazione createAnagraficaUtenteAutorizzazione() {
        return new AnagraficaUtente.Autorizzazione();
    }

    /**
     * Create an instance of {@link DatiBibliografici }
     * 
     */
    public DatiBibliografici createDatiBibliografici() {
        return new DatiBibliografici();
    }

    /**
     * Create an instance of {@link AnagraficaUtente.Nascita }
     * 
     */
    public AnagraficaUtente.Nascita createAnagraficaUtenteNascita() {
        return new AnagraficaUtente.Nascita();
    }

    /**
     * Create an instance of {@link DatiBiblioteca }
     * 
     */
    public DatiBiblioteca createDatiBiblioteca() {
        return new DatiBiblioteca();
    }

    /**
     * Create an instance of {@link AnagraficaUtente.Documento }
     * 
     */
    public AnagraficaUtente.Documento createAnagraficaUtenteDocumento() {
        return new AnagraficaUtente.Documento();
    }

    /**
     * Create an instance of {@link AnagraficaUtente.Residenza }
     * 
     */
    public AnagraficaUtente.Residenza createAnagraficaUtenteResidenza() {
        return new AnagraficaUtente.Residenza();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "colore")
    public JAXBElement<String> createColore(String value) {
        return new JAXBElement<String>(_Colore_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "barcode")
    public JAXBElement<String> createBarcode(String value) {
        return new JAXBElement<String>(_Barcode_QNAME, String.class, null, value);
    }

}
