//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:38:28 PM CEST 
//


package net.bncf.uol2010.utility.xsd.stampante;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}barcode"/>
 *         &lt;element ref="{}colore"/>
 *         &lt;element ref="{}datiBibliografici"/>
 *         &lt;element name="numFascicoli" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numVolumi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dataRichiesta" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="dataInizioPrevista" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="noteUtente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tipoRichiesta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noteBiblioteca" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "barcode",
    "colore",
    "datiBibliografici",
    "numFascicoli",
    "numVolumi",
    "dataRichiesta",
    "dataInizioPrevista",
    "noteUtente",
    "tipoRichiesta",
    "noteBiblioteca"
})
@XmlRootElement(name = "richiesta")
public class Richiesta {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String barcode;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String colore;
    @XmlElement(required = true)
    protected DatiBibliografici datiBibliografici;
    @XmlElement(required = true)
    protected String numFascicoli;
    @XmlElement(required = true)
    protected String numVolumi;
    @XmlElement(required = true)
    protected XMLGregorianCalendar dataRichiesta;
    @XmlElement(required = true)
    protected XMLGregorianCalendar dataInizioPrevista;
    @XmlElement(required = true)
    protected String noteUtente;
    @XmlElement(required = true)
    protected String tipoRichiesta;
    @XmlElement(required = true)
    protected String noteBiblioteca;

    /**
     * Gets the value of the barcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * Sets the value of the barcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarcode(String value) {
        this.barcode = value;
    }

    /**
     * Gets the value of the colore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColore() {
        return colore;
    }

    /**
     * Sets the value of the colore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColore(String value) {
        this.colore = value;
    }

    /**
     * Gets the value of the datiBibliografici property.
     * 
     * @return
     *     possible object is
     *     {@link DatiBibliografici }
     *     
     */
    public DatiBibliografici getDatiBibliografici() {
        return datiBibliografici;
    }

    /**
     * Sets the value of the datiBibliografici property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiBibliografici }
     *     
     */
    public void setDatiBibliografici(DatiBibliografici value) {
        this.datiBibliografici = value;
    }

    /**
     * Gets the value of the numFascicoli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumFascicoli() {
        return numFascicoli;
    }

    /**
     * Sets the value of the numFascicoli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumFascicoli(String value) {
        this.numFascicoli = value;
    }

    /**
     * Gets the value of the numVolumi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumVolumi() {
        return numVolumi;
    }

    /**
     * Sets the value of the numVolumi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumVolumi(String value) {
        this.numVolumi = value;
    }

    /**
     * Gets the value of the dataRichiesta property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataRichiesta() {
        return dataRichiesta;
    }

    /**
     * Sets the value of the dataRichiesta property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataRichiesta(XMLGregorianCalendar value) {
        this.dataRichiesta = value;
    }

    /**
     * Gets the value of the dataInizioPrevista property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataInizioPrevista() {
        return dataInizioPrevista;
    }

    /**
     * Sets the value of the dataInizioPrevista property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataInizioPrevista(XMLGregorianCalendar value) {
        this.dataInizioPrevista = value;
    }

    /**
     * Gets the value of the noteUtente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoteUtente() {
        return noteUtente;
    }

    /**
     * Sets the value of the noteUtente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoteUtente(String value) {
        this.noteUtente = value;
    }

    /**
     * Gets the value of the tipoRichiesta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoRichiesta() {
        return tipoRichiesta;
    }

    /**
     * Sets the value of the tipoRichiesta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoRichiesta(String value) {
        this.tipoRichiesta = value;
    }

    /**
     * Gets the value of the noteBiblioteca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoteBiblioteca() {
        return noteBiblioteca;
    }

    /**
     * Sets the value of the noteBiblioteca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoteBiblioteca(String value) {
        this.noteBiblioteca = value;
    }

}
