//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.07 at 12:38:28 PM CEST 
//


package net.bncf.uol2010.utility.xsd.stampante;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}anagraficaUtente"/>
 *         &lt;element ref="{}datiBiblioteca" minOccurs="0"/>
 *         &lt;element ref="{}richiesta" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "anagraficaUtente",
    "datiBiblioteca",
    "richiesta"
})
@XmlRootElement(name = "stampante")
public class Stampante {

    @XmlElement(required = true)
    protected AnagraficaUtente anagraficaUtente;
    protected DatiBiblioteca datiBiblioteca;
    protected Richiesta richiesta;

    /**
     * Gets the value of the anagraficaUtente property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaUtente }
     *     
     */
    public AnagraficaUtente getAnagraficaUtente() {
        return anagraficaUtente;
    }

    /**
     * Sets the value of the anagraficaUtente property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaUtente }
     *     
     */
    public void setAnagraficaUtente(AnagraficaUtente value) {
        this.anagraficaUtente = value;
    }

    /**
     * Gets the value of the datiBiblioteca property.
     * 
     * @return
     *     possible object is
     *     {@link DatiBiblioteca }
     *     
     */
    public DatiBiblioteca getDatiBiblioteca() {
        return datiBiblioteca;
    }

    /**
     * Sets the value of the datiBiblioteca property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiBiblioteca }
     *     
     */
    public void setDatiBiblioteca(DatiBiblioteca value) {
        this.datiBiblioteca = value;
    }

    /**
     * Gets the value of the richiesta property.
     * 
     * @return
     *     possible object is
     *     {@link Richiesta }
     *     
     */
    public Richiesta getRichiesta() {
        return richiesta;
    }

    /**
     * Sets the value of the richiesta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Richiesta }
     *     
     */
    public void setRichiesta(Richiesta value) {
        this.richiesta = value;
    }

}
