//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.28 at 08:30:15 PM CET 
//


package net.bncf.uol2010.utility.xsd.banco;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.bncf.xsd.banco package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.bncf.xsd.banco
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Banco.Utente }
     * 
     */
    public Banco.Utente createBancoUtente() {
        return new Banco.Utente();
    }

    /**
     * Create an instance of {@link Banco.Utente.Autorizzazioni.Diritto }
     * 
     */
    public Banco.Utente.Autorizzazioni.Diritto createBancoUtenteAutorizzazioniDiritto() {
        return new Banco.Utente.Autorizzazioni.Diritto();
    }

    /**
     * Create an instance of {@link Banco.Utente.Autorizzazioni }
     * 
     */
    public Banco.Utente.Autorizzazioni createBancoUtenteAutorizzazioni() {
        return new Banco.Utente.Autorizzazioni();
    }

    /**
     * Create an instance of {@link Banco }
     * 
     */
    public Banco createBanco() {
        return new Banco();
    }

}
